/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

/** 4/6/2024
 *CSC 229
 * @author Waleed Shahid
 */
public class Homework09 {



        public static void main(String[] args) {
            int n = 1; // INITIALISING TO START with first triangle number
            while (true) { // this loops helps to create infinite triangle nums until the correct one is found

                int triangleNum = n * (n + 1) / 2; // generating triangle number to


                int divisorsTotal = countDivisors(triangleNum); // gathering the number of divisors

                // Check if the count of divisors is over 100
                if (divisorsTotal > 100) {
                    System.out.println("The Recent triangle number to have more than  100 divisors is: " + triangleNum);
                    break; // this helps us to get out of the loop
                }

                n++; // incrementing to generate the next triangle
            }
        }

        private static int countDivisors(int number) {
            int counter = 0; // stating with count of zero

            for (int i = 1; i <= Math.sqrt(number); i++) { // loop through possible divisors
                if (number % i == 0) { // if the result is even, add 2.


                    counter += 2;
                    if (i == number / i) { // we use this if i and number/i are same in this case (divisors)
                        // Correct the count if i is the square root of the number
                        counter--; // decrementing count by 1
                    }
                }
            }
            return counter; // return the total of divisors
        }

    // ToDo 01:  Write an algorithm to solve the following problem
    /*
    The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over one hundred divisors?
    
    */
    
    
}
